name: Main Workflow

on:
  push:
    branches:
      - trunk

jobs:
  isolated:
    name: isolated
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com

      - run: npm clean-install

      - run: npm run compile

      - run: npm publish
